---
# yamllint disable rule:line-length
version: "3.7"

volumes:
  pgadmin: {}
  postgresql-data: {}

services:
  postgres:
    image: bitnami/postgresql:13
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_DATABASE=mdscore
    volumes:
      - ./db-init-scripts:/docker-entrypoint-initdb.d
      - postgresql-data:/bitnami/postgresql
  
  pgadmindb:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin_password
    ports:
      - 8088:80
    volumes:
      - pgadmin:/var/lib/pgadmin   

  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
     - "6379:6379"
    environment:
     - REDIS_REPLICATION_MODE=master
  
  mds-agency:
    image: mds-agency:master-e1aead86
    environment:
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASS=postgres
      - PG_NAME=mdscore
      - REDIS_HOST=redis


  mds-attachment-service:
    image: mds-attachment-service:master-e1aead86
    environment:
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASS=postgres
      - PG_NAME=mdscore
      - REDIS_HOST=redis

    
  mds-audit-api:
    image: mds-audit-api:master-e1aead86
    environment:
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASS=postgres
      - PG_NAME=mdscore
      - REDIS_HOST=redis
  
  mds-audit-service:
    image: mds-audit-service:master-e1aead86
    environment:
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASS=postgres
      - PG_NAME=mdscore
      - REDIS_HOST=redis

  mds-client:
    build: ./mds-client
    image: mds-client    
  
  mds-collector-api:
    image: mds-collector-api:master-e1aead86

  
  mds-collector-service:
    image: mds-collector-service:master-e1aead86
    environment:
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASS=postgres
      - PG_NAME=mdscore
      - REDIS_HOST=redis 

  mds-compliance-api:
    image: mds-compliance-api:master-e1aead86

  
  mds-compliance-service:
    image: mds-compliance-service:master-e1aead86
    environment:
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASS=postgres
      - PG_NAME=mdscore
      - REDIS_HOST=redis

  mds-config-api:
    image: mds-config-api:master-e1aead86


  mds-config-service:
    image: mds-config-service:master-e1aead86
    environment:
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASS=postgres
      - PG_NAME=mdscore
      - REDIS_HOST=redis

  mds-geography-api:
    image: mds-geography-api:master-e1aead86

  
  mds-geography-author-api:
    image: mds-geography-author-api:master-e1aead86

  
  mds-geography-service:
    image: mds-geography-service:master-e1aead86
    environment:
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASS=postgres
      - PG_NAME=mdscore
      - REDIS_HOST=redis

  mds-ingest-service:
    image: mds-ingest-service:master-e1aead86
    environment:
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASS=postgres
      - PG_NAME=mdscore
      - REDIS_HOST=redis


  mds-jurisdiction-api:
    image: mds-jurisdiction-api:master-e1aead86


  mds-jurisdiction-service:
    image: mds-jurisdiction-service:master-e1aead86
    environment:
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASS=postgres
      - PG_NAME=mdscore
      - REDIS_HOST=redis

  mds-policy-author-api:
    image: mds-policy-author-api:master-e1aead86
    
  
  mds-policy-service:
    image: mds-policy-service:master-e1aead86
    environment:
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASS=postgres
      - PG_NAME=mdscore
      - REDIS_HOST=redis

  mds-policy:
    image: mds-policy:master-e1aead86
    
  
  mds-provider-service:
    image: mds-provider-service:master-e1aead86
    environment:
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASS=postgres
      - PG_NAME=mdscore
      - REDIS_HOST=redis

  mds-transaction-api:
    image: mds-transaction-api:master-e1aead86


  mds-transaction-service:
    image: mds-transaction-service:master-e1aead86
    environment:
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASS=postgres
      - PG_NAME=mdscore
      - REDIS_HOST=redis



