---
# yamllint disable rule:line-length
version: "3.7"

services:
  postgres:
    image: bitnami/postgresql:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db-init-scripts:/docker-entrypoint-initdb.d

  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
     - "6379:6379"
    environment:
     - REDIS_REPLICATION_MODE=master
  
  mds-agency:
    image: mds-agency:0.3.15-master-3facd0bc 

  mds-attachment-service:
    image: mds-attachment-service:0.2.10-master-3facd0bc
    
  mds-audit-api:
    image: mds-audit-api:0.3.16-master-3facd0bc 
  
  mds-audit-service:
    image: mds-audit-service:0.2.10-master-3facd0bc
  
  mds-collector-api:
    image: mds-collector-api:0.2.15-master-3facd0bc
  
  mds-collector-service:
    image: mds-collector-service:0.2.11-master-3facd0bc  

  mds-compliance-api:
    image: mds-compliance-api:0.3.16-master-3facd0bc
  
  mds-compliance-service:
    image: mds-compliance-service:0.2.16-master-3facd0bc

  mds-config-api:
    image: mds-config-api:0.6.5-master-3facd0bc

  mds-config-service:
    image: mds-config-service:0.6.5-master-3facd0bc

  mds-geography-api:
    image: mds-geography-api:0.2.15-master-3facd0bc
  
  mds-geography-author-api:
    image: mds-geography-author-api:0.2.15-master-3facd0bc

  
  mds-geography-service:
    image: mds-geography-service:0.2.15-master-3facd0bc 

  mds-ingest-service:
    image: mds-ingest-service:0.2.15-master-3facd0bc
  
  #mds-ingest-migration-processor: #steht gar nicht als container-image auf Github...
    #image:mds-ingest-migration-processor:

  mds-jurisdiction-api:
    image: mds-jurisdiction-api:0.2.15-master-3facd0bc 

  mds-jurisdiction-service:
    image: mds-jurisdiction-service:0.2.10-master-3facd0bc

  mds-policy-author-api:
    image: mds-policy-author-api:0.3.15-master-3facd0bc
  
  mds-policy-service:
    image: mds-policy-service:0.2.15-master-3facd0bc

  mds-policy:
    image: mds-policy:0.3.15-master-3facd0bc
  
  mds-provider-service:
    image: mds-provider-service:0.1.9-master-3facd0bc

  mds-transaction-api:
    image: mds-transaction-api:0.2.16-master-3facd0bc

  mds-transaction-service:
    image: mds-transaction-service:0.2.15-master-3facd0bc
  
  
